---

namespace: bodsch
name: icinga

version: 1.0.2

readme: README.md

authors:
  - Bodo Schulz <bodo@boone-schulz.de>

description: A collection of Ansible roles for the Icinga universe.

license:
  - Apache-2.0

license_file: ''

tags:
  - monitoring
  - icinga
  - icinga2

dependencies:
  bodsch.core: ">=1.1.4"
  bodsch.scm: "*"

repository: https://github.com/bodsch/ansible-collection-icinga
documentation: https://github.com/bodsch/ansible-collection-icinga/README.md
homepage: https://github.com/bodsch/ansible-collection-icinga
issues: https://github.com/bodsch/ansible-collection-icinga/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
