---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: database
    image: "bodsch/ansible-debian:12"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    docker_networks:
      - name: icinga_icingadb
        ipam_config:
          - subnet: "10.13.0.0/24"
            gateway: "10.13.0.2"
    networks:
      - name: icinga_icingadb
        ipv4_address: "10.13.0.10"

  - name: icingadb
    image: "bodsch/ansible-debian:12"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    networks:
      - name: icinga_icingadb
        ipv4_address: "10.13.0.11"

  - name: instance
    image: "bodsch/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - icinga
      - icinga_primary
    networks:
      - name: icinga_icingadb
        ipv4_address: "10.13.0.20"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      gathering: smart
      fact_caching: jsonfile
      fact_caching_timeout: 8640
      fact_caching_connection: "${MOLECULE_EPHEMERAL_DIRECTORY}/ansible_facts"

scenario:
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
