---

- name: snapd
  src: https://github.com/bodsch/ansible-snapd
  version: 1.3.1

- name: monitoring-tools
  src: https://github.com/bodsch/ansible-monitoring-plugins
  version: 1.5.0

- name: mariadb
  src: https://github.com/bodsch/ansible-mariadb
  version: 2.5.0

- name: redis
  src: https://github.com/bodsch/ansible-redis
  version: 1.4.1

...
