---

- name: create icingadb configuration
  ansible.builtin.template:
    src: etc/icingadb/config.yml.j2
    dest: /etc/icingadb/config.yml
    owner: "{{ icingadb_user }}"
    group: "{{ icingadb_group }}"
    mode: 0640
    backup: true
  notify:
    - restart icingadb

- name: create directory for logfiles
  ansible.builtin.file:
    state: directory
    owner: "{{ icingadb_user }}"
    group: "{{ icingadb_group }}"
    mode: 0750
    path: /var/log/icingadb

- name: install database
  ansible.builtin.include_tasks: database/main.yml

...
