---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: database
    image: "ghcr.io/bodsch/docker-ansible/ansible-debian:12"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    tmpfs:
      - /run
      - /tmp
    docker_networks:
      - name: icinga_default
        ipam_config:
          - subnet: "10.11.0.0/24"
            gateway: "10.11.0.2"
    networks:
      - name: icinga_default
        ipv4_address: "10.11.0.10"

  - name: instance
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    tmpfs:
      - /run
      - /tmp
    networks:
      - name: icinga_default
        ipv4_address: "10.11.0.20"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      # gathering: smart
      # fact_caching: jsonfile
      # fact_caching_timeout: 8640
      # fact_caching_connection: ansible_facts

#   name: install
#   ansible_args:
#     - --diff
#     - -v
#   config_options:
#     # Either via config option
#     config_options:
#       tags:
#         run: tag1,tag2,tag3
#     # or env
#     env:
#       ANSIBLE_RUN_TAGS: tag1,tag2,tag3
#     defaults:
#       deprecation_warnings: true
#       stdout_callback: yaml
#       callbacks_enabled: profile_tasks
#       gathering: smart
#       fact_caching: jsonfile
#       fact_caching_timeout: 8640
#       fact_caching_connection: ansible_facts

scenario:
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
