---

- name: snapd
  src: https://github.com/bodsch/ansible-snapd
  version: 1.3.1

- name: php-fpm
  src: https://github.com/bodsch/ansible-php
  version: 2.3.0

- name: nginx
  src: https://github.com/bodsch/ansible-nginx
  version: 0.27.1

- name: mariadb
  src: https://github.com/bodsch/ansible-mariadb
  version: 2.5.0

...
